Install types-requests to placate new mypy
Per instruction!

```
$ mypy emporium
emporium/emporium/validators.py:1: error: Library stubs not installed
for "requests" (or incompatible with Python 3.8)
emporium/emporium/models.py:3: error: Library stubs not installed for
"requests" (or incompatible with Python 3.8)
emporium/emporium/models.py:3: note: Hint: "python3 -m pip install
types-requests"
emporium/emporium/models.py:3: note: (or run "mypy --install-types" to
install all missing stub packages)
emporium/emporium/models.py:3: note: See
https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
Found 2 errors in 2 files (checked 25 source files)
```